# Copyright 2019-2020 The CertiQ authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is automatically generated from a CertiQ compiler pass

from verified_passes.optimize_1q_gates import Optimize1QGate
from giallar.qiskit_wrapper.converter import dag_to_certiq_circ, certiq_circ_to_dag
from qiskit.transpiler.basepasses import TransformationPass

class NewOptimize1QGate(TransformationPass):
    

    def __init__(self, coupling=None):
        super().__init__()
        self.coupling = coupling
        
    def run(self, dag):
        
        
        new_certiq_pass = Optimize1QGate()
        circuit = dag_to_certiq_circ(dag)
        prop = {}
        prop['circ'] = circuit

        try:
            prop['layout'] = self.property_set['layout']
        except:
            pass

        out_prop= new_certiq_pass.run(prop)
        for gate in out_prop['circ'].gate_list:
            print(gate.name, gate.qubits, gate.param)

        new_circuit = out_prop['circ']
        new_dag = certiq_circ_to_dag(new_circuit)

        return new_dag
        

